# Generated by Django 4.2.23 on 2025-07-25 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book_store', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'permissions': [('can_publish_product', 'can publish product')]},
        ),
    ]
